# Generated by Django 4.1.5 on 2023-01-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocli',
            fields=[
                ('idtipo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Cliente')),
                ('nomtipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo de Cliente'))
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Cliente')),
                ('nombrecliente', models.CharField(max_length=30, verbose_name='Nombre de Cliente')),
                ('tipocli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipocli')),
            ],
        ),
        migrations.CreateModel(
            name='Tipomascota',
            fields=[
                ('idtipo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Mascota')),
                ('nomtipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo de Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('codmascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Mascota')),
                ('nombremascota', models.CharField(max_length=30, verbose_name='Nombre de la Mascota')),
                ('tipomascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipomascota')),
            ],
            
        ),

    ]
