# Generated by Django 4.1.5 on 2023-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocli',
            fields=[
                ('idtipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Cliente')),
                ('nomtipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo de Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
