# Generated by Django 4.1.5 on 2023-01-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipocli_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocli',
            name='idtipo',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Cliente'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutcliente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Rut del Cliente')),
                ('nombrecliente', models.CharField(max_length=40, verbose_name='Nombre de Cliente')),
                ('tipocli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipocli')),
            ],
        ),
    ]
