# Generated by Django 4.1.5 on 2023-01-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tipocli_idtipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipomascota',
            fields=[
                ('idtipo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Mascota')),
                ('nomtipo', models.CharField(max_length=30, verbose_name='Nombre del Tipo de Mascota')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rutcliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Cliente'),
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('codmascota', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo de Mascota')),
                ('nombremascota', models.CharField(max_length=30, verbose_name='Nombre de la Mascota')),
                ('tipomascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipomascota')),
            ],
        ),
    ]
