# Generated by Django 4.1.5 on 2023-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipomascota_alter_cliente_rutcliente_mascotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='codmascota',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo de Mascota'),
        ),
    ]
