# Generated by Django 4.1.5 on 2023-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mascotas_codmascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
