# Generated by Django 4.1.5 on 2023-01-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mascotas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.IntegerField(null=True, verbose_name='Telefono de Contacto'),
        ),
    ]
